#!/bin/bash
#SBATCH -n 24
#SBATCH -t 00:10:00
#SBATCH --constraint=haswell
#SBATCH --reservation=bootcamp

# grid definition

# grid-size in x and y-direction
m=1000 
n=1000

# mesh size
dx=0.1
dy=0.1

# time step
dt=0.001

# wave propagation speed
c=0.3

# damping
zeta=0.0

# number of time steps, output interval
nt=200000
nt_i=10000


# initial condition: a cosine bump around (f0x0,f0y0) with radius f0r0
f0x0=50.0
f0y0=100.0
f0r0=20.0

outfile=wave.h5

echo "Starting run at " $(date)
time srun ./wave $m $n $dx $dy $nt $dt $c $zeta $f0x0 $f0y0 $f0r0 $nt_i $outfile

echo "Fished run at " $(date) ", starting post-processing"
perl h52anim.pl -p 4 $outfile u
echo $(date)

